// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrlhM4zwjJ9zhyPec8zVpxj3Ubdj0D1Hw',
    appId: '1:528595991946:web:40bd9ed8f7b74e28565c73',
    messagingSenderId: '528595991946',
    projectId: 'journalyze-155d8',
    authDomain: 'journalyze-155d8.firebaseapp.com',
    storageBucket: 'journalyze-155d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfF_nC6nipyZg-JTj-9rc7Zc6D9FC9Dw',
    appId: '1:528595991946:android:132a4cc024d469e0565c73',
    messagingSenderId: '528595991946',
    projectId: 'journalyze-155d8',
    storageBucket: 'journalyze-155d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8QuxoXHL6DU12BYEyE-Rzs4RV-JSbE0g',
    appId: '1:528595991946:ios:3c78192a3a368870565c73',
    messagingSenderId: '528595991946',
    projectId: 'journalyze-155d8',
    storageBucket: 'journalyze-155d8.firebasestorage.app',
    iosBundleId: 'com.example.journalyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8QuxoXHL6DU12BYEyE-Rzs4RV-JSbE0g',
    appId: '1:528595991946:ios:3c78192a3a368870565c73',
    messagingSenderId: '528595991946',
    projectId: 'journalyze-155d8',
    storageBucket: 'journalyze-155d8.firebasestorage.app',
    iosBundleId: 'com.example.journalyze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrlhM4zwjJ9zhyPec8zVpxj3Ubdj0D1Hw',
    appId: '1:528595991946:web:1a71f51b09b8f36c565c73',
    messagingSenderId: '528595991946',
    projectId: 'journalyze-155d8',
    authDomain: 'journalyze-155d8.firebaseapp.com',
    storageBucket: 'journalyze-155d8.firebasestorage.app',
  );
}
